export const BookingCars = [
    {id:0,
    title:"Audi A3 Black", 
    type:"Sedan", 
    users:4, 
    engine: "manual", 
    rent: 400, 
    img:"/imgs/audi-a3-blakc.png",
    class:"new"
    },
    {id:1,
    title:"Suzuki Siaz Blue", 
    type:"Sedan", 
    users:4,
    engine: "manual", 
    rent: 400, 
    img:"/imgs/maruti-suzuki.png",
    class:"new"
    },
    {id:2,
    title:"Audi A3 Black", 
    type:"Sedan", 
    users:4,
    engine: "automatic", 
    rent: 400, 
    img:"/imgs/audi-a3-blakc.png",
    class:"old"
    },
    {id:3,
    title:"Mercedes-Benz GlE skyBlue", 
    type:"SUV", 
    users:4,
    engine: "automatic", 
    rent: 400, 
    img:"/imgs/mercedes-benz-m.png",
    class:"old"
    },
    {id:4,
    title:"Audi Q6 White", 
    type:"SUV", 
    users:3,
    engine: "automatic", 
    rent: 400, 
    img:"/imgs/audi-q6.png",
    class:"new"
    },
    {id:5,
    title:"Mercedes-Benz GlE skyBlue", 
    type:"SUV", 
    users:4,
    engine: "automatic", 
    rent: 400, 
    img:"/imgs/mercedes-benz-m.png",
    class:"old"
    },
    {id:6,
    title:"Audi Q6 White", 
    type:"SUV", 
    users:3,
    engine: "automatic", 
    rent: 400, 
    img:"/imgs/audi-q6.png",
    class:"new"
    },
    {id:7,
    title:"Mercedes-Benz GlE skyBlue", 
    type:"SUV", 
    users:4,
    engine: "automatic", 
    rent: 400, 
    img:"/imgs/mercedes-benz-m.png",
    class:"new"
    },
    {id:8,
    title:"Audi Q6 White", 
    type:"SUV", 
    users:3,
    engine: "automatic", 
    rent: 400, 
    img:"/imgs/audi-q6.png",
    class:"old"
    },
  ];
  
 export const members = [
    {id:0, name:"Killan James", img:'Killan-James.png'},
    {id:1, name:"Desian Tam", img:'Desian-Tam.png'},
    {id:2, name:"Ahmed Medi", img:'AhmedMedi.png'},
    {id:3, name:"Claudia Maudi", img:'ClaudiaMaudi.png'},
    {id:4, name:"MilieNose", img:'MilieNose.png'},
    {id:5, name:"Ikhsan SD", img:'IkhsanSD.png'},
    {id:6, name:"Aditya", img:'Aditya.png'},
  ];